#!/usr/bin/env python3
"""
csv_to_header.py  –  Convert an 8×8 pixel-art CSV to a colors.h Arduino header
================================================================================
Usage
-----
    python csv_to_header.py  my_art.csv              # single frame
    python csv_to_header.py  frame1.csv frame2.csv   # animation (multiple frames)

The CSV must contain 8 rows × 8 columns of 6-digit hex colour codes (no '#').
Export from the Excel template via  File → Save As → CSV UTF-8.

Output
------
colors.h  – placed in the same directory as this script.
Place colors.h in your Arduino sketch folder before compiling.
"""

import sys
import csv
import re
import os
from datetime import datetime

HEX_RE = re.compile(r'^[0-9A-Fa-f]{6}$')

def parse_csv(path: str) -> list[list[str]]:
    """Read a CSV and return an 8×8 list of hex strings."""
    rows = []
    with open(path, newline='', encoding='utf-8-sig') as f:
        reader = csv.reader(f)
        for raw_row in reader:
            # Strip whitespace, skip empty rows
            row = [cell.strip().lstrip('#').upper() for cell in raw_row]
            row = [c for c in row if c]           # drop empty cells
            if not row:
                continue
            rows.append(row)

    if len(rows) != 8:
        raise ValueError(f"{path}: expected 8 rows, got {len(rows)}")

    grid = []
    for i, row in enumerate(rows):
        if len(row) != 8:
            raise ValueError(f"{path} row {i+1}: expected 8 columns, got {len(row)}")
        for j, cell in enumerate(row):
            if not HEX_RE.match(cell):
                raise ValueError(
                    f"{path} row {i+1} col {j+1}: '{cell}' is not a valid 6-digit hex colour"
                )
        grid.append(row)

    return grid


def grid_to_c_array(grid: list[list[str]], frame_idx: int) -> str:
    """Render one 8×8 grid as a C uint32_t[64] initialiser."""
    lines = [f"  // Frame {frame_idx}"]
    for row in grid:
        hex_vals = ", ".join(f"0x{c}" for c in row)
        lines.append(f"  {hex_vals},")
    # Remove trailing comma from last element of last row
    last = lines[-1]
    if last.endswith(","):
        lines[-1] = last[:-1]
    return "\n".join(lines)


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    csv_files = sys.argv[1:]
    frames = []
    for path in csv_files:
        print(f"Reading {path} …")
        frames.append(parse_csv(path))

    frame_count = len(frames)
    out_dir = os.path.dirname(os.path.abspath(sys.argv[1]))
    out_path = os.path.join(out_dir, "colors.h")

    lines = [
        "// colors.h – AUTO-GENERATED by csv_to_header.py",
        f"// Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"// Sources:   {', '.join(os.path.basename(p) for p in csv_files)}",
        "",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define FRAME_COUNT {frame_count}",
        "",
        "// Each value is a 24-bit RGB colour: 0xRRGGBB",
        f"static const uint32_t PIXEL_FRAMES[{frame_count}][64] PROGMEM = {{",
    ]

    for idx, grid in enumerate(frames):
        lines.append("  {")
        lines.append(grid_to_c_array(grid, idx))
        closing = "  }," if idx < frame_count - 1 else "  }"
        lines.append(closing)

    lines += ["};", ""]

    with open(out_path, "w") as f:
        f.write("\n".join(lines))

    print(f"✓  Written {out_path}  ({frame_count} frame{'s' if frame_count != 1 else ''})")


if __name__ == "__main__":
    main()
